training:
  num_epochs: 30
  save_name: "trained_competition.pt"

#dataset names: "Flowers", "Cub", "Dogs", "Airplanes", "Food"

dataset: "Train_Competition"

#model name: "CLIP", "Vgg19", "ResNet50"

model: "CLIP"

pretrained:
  pre_t: False
  load: ".pt"

data:
  batch_size_train: 128
  batch_size_test: 256
  num_workers: 4
  output_dim: 100
  path_root: "competition_data/train"


logger:
  wandb: True

competition: True