
#model name: "CLIP", "Vgg19", "ResNet50"

model: "ResNet50"

pretrained:
  pre_t: True
  load: "trained_competition.pt"

data:
  batch_size_train: 64
  batch_size_test: 256
  num_workers: 4
  output_dim: 3
  path_root: "competition_dataset/train"

logger:
  wandb: False
