training:
  num_epochs: 20
  save_name: "trained_Dogs.pt"


#dataset names: "Flowers", OR "Train_Competition" for Cub, Dogs and Cars

dataset: "Train_Competition"

#model name: "CLIP", "Vgg19", "ResNet50"

model: "Vgg19"

pretrained:
  pre_t: False
  load: ".pt"

data:
  batch_size_train: 64
  batch_size_test: 256
  num_workers: 4
  output_dim: 120
  path_root: "Stanford_Dog"


logger:
  wandb: True
