
#model name: "CLIP", "Vgg19", "ResNet50"

model: "Vgg19"

pretrained:
  pre_t: True
  load: "trained_competition.pt"

data:
  batch_size_train: 64
  batch_size_test: 512
  num_workers: 4
  output_dim: 100
  path_root: "competition_data/test"

logger:
  wandb: False
