training:
  num_epochs: 2
  save_name: "trained_competition.pt"

#dataset names: "Flowers", "Cub", "Dogs", "Airplanes", "Food"

dataset: "Train_Competition"

#model name: "CLIP", "Vgg19", "ResNet50"

model: "ResNet50"

pretrained:
  pre_t: False
  load: ".pt"

data:
  batch_size_train: 64
  batch_size_test: 256
  num_workers: 4
  output_dim: 3
  path_root: "competition_dataset/train"


logger:
  wandb: True

competition: True