training:
  num_epochs: 30
  save_name: "trained_flowers.pt"

#dataset names: "Flowers", "Cub", "Dogs", "Airplanes", "Food"

dataset: "Flowers"

#model name: "CLIP", "Vgg19", "ResNet50"

model: "Vgg19"

pretrained:
  pre_t: False
  load: "trained_flowers.pt"

data:
  batch_size_train: 32
  batch_size_test: 32
  num_workers: 4
  output_dim: 102
  path_root: None

logger:
  wandb: True

competition: False